#!/bin/sh

/usr/bin/invoke_app "$@" -t rstudio \
                         -u R-4.0.5 \
                         -u rstudio-server-1.4.1717 \
                         -u wrwroxy-0.2 \
                         -w headless \
                         -r none \
                         -c "wrwroxy --listenHost 0.0.0.0 --listenPort 8000 --forwardHost 127.0.0.1 --forwardPort 8001 --connectTime 60 --rstudio-login --modify-header --loglevel WARNING" \
                         -C rserverHUB.sh
